export const GENDERS = [
  'Top',
  'Bottom',
  'Secret third thing',
  'Evil',
  'Very Evil',
  'Too Evil',
  'Good',
  'Very Good',
  'Too Good',
  'Cat',
  'Dog',
  'Air',
  'Wind',
  'Fire',
  'Earth',
  'Electricity',
  'Gravity',
  'Pizza',
  'Ham and cheese sandwich',
  'A stone with googly eyes',
  'Autistic robot',
  'ADHD Gremlin',
  'Lesbian except for David Tennant',
  'Heterosexual except for Henry Cavil',
  'Smol dog',
  'Big doge',
  'Everything everywhere all at once',
  'Big scary werewolf that actually has an anxiety disorder and is more scared of you than you are of it',
  'I am just testing a new font',
  'Widsom',
  'Wizard',
  'Mage',
  'Warlock',
  'Bard',
  'Australian',
  'British',
  'French',
  'Polish',
  'Eating book pages to fix low fiber in diet',
  'Eating bolts to fix low iron in diet',
  'Mutual Assured Headache',
  'I am sending a PR with more genders',
  'Lesbian knight',
  'Gay Ranger',
  "I don't have one, where can I get one of those?",
  "I don't have one and I am not interested",
  'Nah-uh I don\'t do those',
  'I have been clean of gender for over a year now',
  'STOP CALLING ME I DONT WANT ANY OF THOSE GENDERS I AM NOT INTERESTED I SWEAR TO GOO',
  'Piss',
  'Shit',
  'Ass',
  'Dicke & Balls',
  'Deez nuts',
  'Masking',
  'this gender is not genuine',
  'Unicorn',
  'Dragon',
  'Snake',
  'Mine was programmed by Bethesa',
  'Mine was programmed by Ubisofr',
  'Vriska',
  'The impostor from among us',
  'Fox',
  'Honk',
  'God',
  'I am going to kill god',
  'A pumpkin full of meat would fix me',
  'Tod',
  'Todd',
  "gender isn't real, it can't hurt you",
  'Yes',
  'No',
  'Up',
  'Down',
  'Strange',
  'Charm',
  'Wait those were quark types',
]
