# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and push a new beta to TestFlight"
  lane :beta do
    match(
      type: 'appstore',
      readonly: ENV['CI']
    )
    changelog_from_git_commits
    build_app(workspace: "Wafrn.xcworkspace", scheme: "Wafrn")
    upload_to_testflight(distribute_external: true, groups: ['Wafrn TestFlight'])
  end
end
