when:
  - event: manual

steps:
  - name: build
    image: ubuntu:latest
    environment:
      NODE_OPTIONS: '--openssl-legacy-provider --max_old_space_size=4096'
      UNSIGNED_APK: 1
    commands:
      - apt-get update -y
      - apt-get install -y xz-utils openjdk-17-jdk-headless curl unzip bash coreutils
      - curl "https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip" > commandlinetoolst.zip
      - mkdir -p ${HOME}/android
      - unzip commandlinetoolst.zip -d ${HOME}/android
      - export ANDROID_HOME=${HOME}/android
      - export PATH="$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
      - curl "https://nodejs.org/dist/v22.14.0/node-v22.14.0-linux-x64.tar.xz" > node.tar.xz
      - mkdir -p ${HOME}/opt
      - tar xf node.tar.xz -C ${HOME}/opt
      - export CI=1
      - export PATH="${PATH}:${HOME}/opt/node-v22.14.0-linux-x64/bin:${HOME}/.node/bin"
      - npm config set prefix "${HOME}/.node"
      - npm install
      - npm ci && npm rebuild lightningcss
      - ./scripts/android_build.sh dev

  - name: publish
    image: woodpeckerci/plugin-release
    settings:
      draft: true
      title: 'Woodpecker CI Release'
      note: 'Release generated by Woodpecker CI'
      files:
        - android/app/build/outputs/apk/debug/*.apk
      api_key:
        from_secret: WOODPECKER_RELEASE_TOKEN
