when:
  - event: manual

steps:
  - name: build
    image: runmymind/docker-android-sdk:latest
    environment:
      NODE_OPTIONS: '--openssl-legacy-provider --max_old_space_size=4096'
      UNSIGNED_APK: 1
    commands:
      # - sed -i '2s/^# *//' /etc/apk/repositories
      # - apk update
      # - apk add bash coreutils
      # - apk add openjdk17 ninja-build xz python3 android-tools
      - apt-get update -y && apt-get install -y xz-utils
      - curl "https://nodejs.org/dist/v22.14.0/node-v22.14.0-linux-x64.tar.xz" > node.tar.xz
      - mkdir -p ${HOME}/opt
      - tar xf node.tar.xz -C ${HOME}/opt
      - export CI=1
      - export PATH="${PATH}:${HOME}/opt/node-v22.14.0-linux-x64/bin:${HOME}/.node/bin"
      - npm config set prefix "${HOME}/.node"
      - npm install
      - npm ci && npm rebuild lightningcss
      - sudo chmod +x ./scripts/android_build.sh
      - sudo chmod +x ./android/gradlew
      - /bin/bash ./scripts/android_build.sh dev

  - name: publish
    image: woodpeckerci/plugin-release
    settings:
      draft: true
      title: 'Woodpecker CI Release'
      note: 'Release generated by Woodpecker CI'
      files:
        - android/app/build/outputs/apk/debug/*.apk
      api_key:
        from_secret: WOODPECKER_RELEASE_TOKEN
