when:
  - event: manual

steps:
  - name: build
    image: codeberg.org/native-ci/android-ndk:latest
    commands:
      - npm ci && npm rebuild lightningcss
      - bash ./scripts/android_build.sh dev
