name: Create new version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Configure git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Check if tag exists
        run: |
          if git rev-parse v${{ steps.get_version.outputs.version }} >/dev/null 2>&1; then
            echo "Tag v${{ steps.get_version.outputs.version }} already exists"
          fi

      - name: Update native versions
        run: |
          ./scripts/updateVersion.ts ${{ steps.get_version.outputs.version }}

      - name: Commit changes
        run: |
          # Only commit if there are changes in the working tree
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update native versions"
            git push
          fi

      - name: Remove existing tag if exists
        run: |
          if git rev-parse v${{ steps.get_version.outputs.version }} >/dev/null 2>&1; then
            git push --delete origin v${{ steps.get_version.outputs.version }}
            git tag -d v${{ steps.get_version.outputs.version }}
          fi

      - name: Create tag
        run: |
          git tag -a v${{ steps.get_version.outputs.version }} -m "Version ${{ steps.get_version.outputs.version }}"
          git push origin v${{ steps.get_version.outputs.version }}
